language: python

python:
  - "2.7"

env:
  - TOX_ENV=flake8
  - TOX_ENV=py27

before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy

# command to install dependencies

install:
  - pip install travis-sphinx
  - pip install numpydoc
  - pip install sphinx_rtd_theme
  - pip install tox

notifications:
  slack: qtim:jp1UTPVP5wscM2R6eyFHJIb4

script:
  - tox -e $TOX_ENV
  - travis-sphinx build --nowarn
    
after_success:
  - travis-sphinx deploy
